/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type __s8 = ::std::os::raw::c_char;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __kernel_fd_set {
    pub fds_bits: [::std::os::raw::c_ulong; 16usize],
}
impl ::std::default::Default for __kernel_fd_set {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __kernel_sighandler_t =
    ::std::option::Option<extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type __kernel_key_t = ::std::os::raw::c_int;
pub type __kernel_mqd_t = ::std::os::raw::c_int;
pub type __kernel_old_uid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_gid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_dev_t = ::std::os::raw::c_ulong;
pub type __kernel_long_t = ::std::os::raw::c_long;
pub type __kernel_ulong_t = ::std::os::raw::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = ::std::os::raw::c_uint;
pub type __kernel_pid_t = ::std::os::raw::c_int;
pub type __kernel_ipc_pid_t = ::std::os::raw::c_int;
pub type __kernel_uid_t = ::std::os::raw::c_uint;
pub type __kernel_gid_t = ::std::os::raw::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = ::std::os::raw::c_int;
pub type __kernel_uid32_t = ::std::os::raw::c_uint;
pub type __kernel_gid32_t = ::std::os::raw::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __kernel_fsid_t {
    pub val: [::std::os::raw::c_int; 2usize],
}
impl ::std::default::Default for __kernel_fsid_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = ::std::os::raw::c_longlong;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = ::std::os::raw::c_int;
pub type __kernel_clockid_t = ::std::os::raw::c_int;
pub type __kernel_caddr_t = *mut ::std::os::raw::c_char;
pub type __kernel_uid16_t = ::std::os::raw::c_ushort;
pub type __kernel_gid16_t = ::std::os::raw::c_ushort;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfattr {
    pub nfa_len: __u16,
    pub nfa_type: __u16,
}
impl ::std::default::Default for nfattr {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum nfnetlink_groups {
    NFNLGRP_NONE = 0,
    NFNLGRP_CONNTRACK_NEW = 1,
    NFNLGRP_CONNTRACK_UPDATE = 2,
    NFNLGRP_CONNTRACK_DESTROY = 3,
    NFNLGRP_CONNTRACK_EXP_NEW = 4,
    NFNLGRP_CONNTRACK_EXP_UPDATE = 5,
    NFNLGRP_CONNTRACK_EXP_DESTROY = 6,
    NFNLGRP_NFTABLES = 7,
    NFNLGRP_ACCT_QUOTA = 8,
    NFNLGRP_NFTRACE = 9,
    __NFNLGRP_MAX = 10,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfgenmsg {
    pub nfgen_family: __u8,
    pub version: __u8,
    pub res_id: __be16,
}
impl ::std::default::Default for nfgenmsg {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum nfqnl_msg_types {
    NFQNL_MSG_PACKET = 0,
    NFQNL_MSG_VERDICT = 1,
    NFQNL_MSG_CONFIG = 2,
    NFQNL_MSG_VERDICT_BATCH = 3,
    NFQNL_MSG_MAX = 4,
}
#[repr(C, packed)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfqnl_msg_packet_hdr {
    pub packet_id: __be32,
    pub hw_protocol: __be16,
    pub hook: __u8,
}
impl ::std::default::Default for nfqnl_msg_packet_hdr {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfqnl_msg_packet_hw {
    pub hw_addrlen: __be16,
    pub _pad: __u16,
    pub hw_addr: [__u8; 8usize],
}
impl ::std::default::Default for nfqnl_msg_packet_hw {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfqnl_msg_packet_timestamp {
    pub sec: __be64,
    pub usec: __be64,
}
impl ::std::default::Default for nfqnl_msg_packet_timestamp {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum nfqnl_vlan_attr {
    NFQA_VLAN_UNSPEC = 0,
    NFQA_VLAN_PROTO = 1,
    NFQA_VLAN_TCI = 2,
    __NFQA_VLAN_MAX = 3,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum nfqnl_attr_type {
    NFQA_UNSPEC = 0,
    NFQA_PACKET_HDR = 1,
    NFQA_VERDICT_HDR = 2,
    NFQA_MARK = 3,
    NFQA_TIMESTAMP = 4,
    NFQA_IFINDEX_INDEV = 5,
    NFQA_IFINDEX_OUTDEV = 6,
    NFQA_IFINDEX_PHYSINDEV = 7,
    NFQA_IFINDEX_PHYSOUTDEV = 8,
    NFQA_HWADDR = 9,
    NFQA_PAYLOAD = 10,
    NFQA_CT = 11,
    NFQA_CT_INFO = 12,
    NFQA_CAP_LEN = 13,
    NFQA_SKB_INFO = 14,
    NFQA_EXP = 15,
    NFQA_UID = 16,
    NFQA_GID = 17,
    NFQA_SECCTX = 18,
    NFQA_VLAN = 19,
    NFQA_L2HDR = 20,
    __NFQA_MAX = 21,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfqnl_msg_verdict_hdr {
    pub verdict: __be32,
    pub id: __be32,
}
impl ::std::default::Default for nfqnl_msg_verdict_hdr {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum nfqnl_msg_config_cmds {
    NFQNL_CFG_CMD_NONE = 0,
    NFQNL_CFG_CMD_BIND = 1,
    NFQNL_CFG_CMD_UNBIND = 2,
    NFQNL_CFG_CMD_PF_BIND = 3,
    NFQNL_CFG_CMD_PF_UNBIND = 4,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfqnl_msg_config_cmd {
    pub command: __u8,
    pub _pad: __u8,
    pub pf: __be16,
}
impl ::std::default::Default for nfqnl_msg_config_cmd {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum nfqnl_config_mode {
    NFQNL_COPY_NONE = 0,
    NFQNL_COPY_META = 1,
    NFQNL_COPY_PACKET = 2,
}
#[repr(C, packed)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nfqnl_msg_config_params {
    pub copy_range: __be32,
    pub copy_mode: __u8,
}
impl ::std::default::Default for nfqnl_msg_config_params {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum nfqnl_attr_config {
    NFQA_CFG_UNSPEC = 0,
    NFQA_CFG_CMD = 1,
    NFQA_CFG_PARAMS = 2,
    NFQA_CFG_QUEUE_MAXLEN = 3,
    NFQA_CFG_MASK = 4,
    NFQA_CFG_FLAGS = 5,
    __NFQA_CFG_MAX = 6,
}
